#配置连接数据库
server:
  port: 8080

spring:
  mvc:
    view:
      prefix: classpath:templates/
      suffix: .html

  datasource:
    url: jdbc:mysql://localhost:3306/easybuy?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456


#配置mybatis
mybatis:
  type-aliases-package: com.wy.entity
  mapper-locations: classpath:xml/*.xml
